on:
  release:
    types: [created]

name: Upload binaries
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.4'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        run: |
          make release
      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" bin/*
